const test=require('node:test');
const assert=require('node:assert/strict');
const catalog=require('../data/catalog.json');
const {classify}=require('../assets/matcher.js');
function program(id){const p=structuredClone(catalog.programs.find(p=>p.id===id));for(const c of ['requirements','english','intakes','tuition','professional_registration'])p[c]=catalog[c].find(x=>x.program_id===id);for(const c of ['entry_routes','qualifications'])p[c]=catalog[c].filter(x=>x.program_id===id);for(const c of ['scholarships','accommodation'])p[c]=catalog[c].filter(x=>x.university_id===p.university_id);return p;}
const check=(id,f)=>classify(program(id),f);
test('화학 없음: JCU는 검토 가능, Monash Direct는 제외',()=>{assert.equal(check('jcu-bpharm-hons',{chemistry:'no',route:'direct'}).state,'match');assert.equal(check('monash-bpharm-hons',{chemistry:'no',route:'direct'}).state,'excluded');});
test('화학 미확인 대학은 필수 아님으로 통과시키지 않음',()=>assert.equal(check('latrobe-bpharm-hons',{chemistry:'no'}).state,'pending'));
test('IELTS 6.5 필터 실제 차등: UQ 통과, Canberra 7.0 제외',()=>{assert.equal(check('uq-bpharm-hons',{english:'6.5'}).state,'match');assert.equal(check('canberra-bpharm-hons',{english:'6.5'}).state,'excluded');});
test('Newcastle 영어 공식자료 충돌은 자동 통과시키지 않음',()=>assert.equal(check('newcastle-bpharm-hons',{english:'7'}).state,'pending'));
test('UTas 2027 영어 IELTS 6.5는 공식 확인값으로 필터 통과',()=>assert.equal(check('utas-bpharm-hons',{english:'6.5'}).state,'match'));
test('Sydney CSAT Pharmacy 346 경계값',()=>{assert.equal(check('sydney-bpharm-hons',{qualification:'csat',score:'346',route:'direct'}).state,'match');assert.equal(check('sydney-bpharm-hons',{qualification:'csat',score:'345',route:'direct'}).state,'excluded');});
test('전체 경로 모드: 낮은 Direct 점수라도 Foundation은 별도 검토',()=>{const r=check('sydney-bpharm-hons',{qualification:'csat',score:'345'});assert.equal(r.state,'pending');assert.ok(r.unknown.some(x=>x.includes('Direct 조건 미충족')));});
test('모든 학교에 수능 숫자를 채우지 않음',()=>assert.equal(check('uq-bpharm-hons',{qualification:'csat',score:'500',route:'direct'}).state,'pending'));
test('Sydney 내신만으로 Direct 평가 불가, Foundation 선택은 개별 확인',()=>{assert.equal(check('sydney-bpharm-hons',{qualification:'korean_high_school',route:'direct'}).state,'excluded');assert.equal(check('sydney-bpharm-hons',{qualification:'korean_high_school',route:'foundation'}).state,'pending');});
test('UQ 7월 빠른 과정과 2월 빠른 과정을 구분',()=>{assert.equal(check('uq-bpharm-hons',{duration:'fast',intake:'7'}).state,'match');assert.equal(check('uq-bpharm-hons',{duration:'fast',intake:'2'}).state,'excluded');});
test('7월 본과와 2월 Accelerated Foundation 시작을 혼동하지 않음',()=>{assert.equal(check('uq-bpharm-hons',{route:'foundation',intake:'2'}).state,'match');assert.equal(check('uq-bpharm-hons',{route:'foundation',intake:'7'}).state,'excluded');});
test('UQ 신설 PharmD 미승인 상태는 기본적으로 pending',()=>assert.equal(check('uq-pharmd',{}).state,'pending'));
test('신설 PharmD는 기존 BPharm 수능을 복사하지 않음',()=>assert.equal(check('uq-pharmd',{qualification:'csat',score:'999',route:'direct'}).state,'pending'));
test('등록 실무 통합 필터: Monash와 UNSW 구별',()=>{assert.equal(check('monash-bpharm-hons',{structure:'integrated'}).state,'match');assert.equal(check('unsw-bpharm-hons',{structure:'integrated'}).state,'excluded');});
test('4년 Exit 미확인 Sydney를 자동 통과시키지 않음',()=>{assert.equal(check('monash-bpharm-hons',{structure:'exit'}).state,'match');assert.equal(check('sydney-bpharm-hons',{structure:'exit'}).state,'pending');});
test('졸업자는 Monash GE도 추가 대학 과목 심사 필요',()=>{assert.equal(check('monash-bpharm-hons',{qualification:'graduate'}).state,'pending');assert.equal(check('jcu-bpharm-hons',{qualification:'graduate'}).state,'excluded');});
test('UNSW 20%는 한국 국적 기본 장학 필터에 포함되지 않음',()=>{assert.equal(check('unsw-bpharm-hons',{cost:'20'}).state,'excluded');assert.equal(check('sydney-bpharm-hons',{cost:'20'}).state,'match');});
test('Curtin 2027 Global Merit 20%는 약대 장학 필터에 포함',()=>assert.equal(check('curtin-bpharm-hons',{cost:'20'}).state,'match'));
test('Newcastle 20% International Excellence는 Pharmacy 제외',()=>assert.equal(check('newcastle-bpharm-hons',{cost:'20'}).state,'excluded'));
test('Griffith 공개 Diploma 경로는 Griffith College만 유지',()=>{assert.equal(check('griffith-bpharm-hons',{route:'diploma'}).state,'match');const r=catalog.entry_routes.filter(x=>x.program_id==='griffith-bpharm-hons'&&x.type==='diploma');assert.equal(r.length,1);assert.equal(r[0].id,'griffith-college');assert.equal(r[0].credit.value,80);assert.equal(catalog.entry_routes.some(x=>x.id==='unicentre-korea'),false);});
test('RMIT Associate Degree는 1년 Diploma가 아님',()=>{const r=catalog.entry_routes.find(x=>x.id==='rmit-associate');assert.equal(r.type,'other');assert.equal(r.availability.status,'pending_2027');});
test('공식 총학비를 연간금액×기간으로 생성하지 않음',()=>{assert.equal(catalog.tuition.find(x=>x.program_id==='utas-bpharm-hons').official_total.value,198050);assert.equal(catalog.tuition.find(x=>x.program_id==='sydney-bpharm-hons').official_total.value,null);});

test('Griffith 2026 H1 점수를 2027 충족으로 판정하지 않음',()=>{assert.equal(check('griffith-bpharm-hons',{qualification:'csat',score:'400',route:'direct'}).state,'pending');assert.equal(check('griffith-bpharm-hons',{qualification:'csat',score:'200',route:'direct'}).state,'pending');});
test('Curtin 3년 9개월과 졸업 후 internship 구별',()=>{assert.equal(check('curtin-bpharm-hons',{structure:'3.75'}).state,'match');assert.equal(check('curtin-bpharm-hons',{structure:'integrated'}).state,'excluded');});
test('UniSQ 2027은 3년 가속 과정으로 포함하지 않음',()=>assert.equal(check('unisq-bpharm-hons',{duration:'fast'}).state,'excluded'));
